services:
  s3-minio:
    image: quay.io/minio/minio
    container_name: s3-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  # See. https://stackoverflow.com/questions/66412289/minio-add-a-public-bucket-with-docker-compose
  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - s3-minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc config host add myminio http://s3-minio:9000 admin password;
      mc rm -r --force myminio/test-bucket;
      mc mb myminio/test-bucket;
      mc anonymous set public myminio/test-bucket;
      exit 0;"

  lambda:
    build:
      context: ./lambda
    container_name: lambda
    platform: linux/amd64
    ports:
      - "9002:8080" # Lambda の RIE が 8080 ポートで待ち受けているため、ホスト側のポートを 8080 にバインドする
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    env_file:
      - .env
    depends_on:
      - s3-minio
